ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_role;
DROP INDEX IF EXISTS idx_users_permissions;
DROP INDEX IF EXISTS idx_users_role;
ALTER TABLE users DROP COLUMN IF EXISTS version;
ALTER TABLE users DROP COLUMN IF EXISTS permissions;
ALTER TABLE users DROP COLUMN IF EXISTS role;
