ALTER TABLE leagues
ADD COLUMN IF NOT EXISTS game_type VARCHAR(50) NOT NULL DEFAULT 'F1 25',
ADD COLUMN IF NOT EXISTS platform VARCHAR(50) NOT NULL DEFAULT 'PC',
ADD COLUMN IF NOT EXISTS max_teams INTEGER NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS rules TEXT,
ADD COLUMN IF NOT EXISTS prize_info TEXT,
ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS banner_url VARCHAR(500),
ADD COLUMN IF NOT EXISTS registration_start TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS registration_end TIMESTAMP WITH TIME ZONE;
